export function AiDocsBanner() {
  return (
    <div className="border border-amber-300/60 bg-amber-50 rounded-lg p-4 mb-6 dark:border-amber-700/40 dark:bg-amber-900/20">
      <p className="text-amber-800 text-sm font-semibold dark:text-amber-300">
        AI-Generated Placeholder
      </p>
      <p className="text-amber-700 text-sm mt-1 dark:text-amber-400/80">
        This documentation was generated by AI as scaffolding and may contain inaccuracies.
        Hand-written documentation is coming soon.
      </p>
    </div>
  );
}
