// Cloudflare Workers adapter
//
// Primary deployment target. Generates a Workers-compatible entry point
// and wrangler.jsonc configuration. See design/11-platform.md §"Cloudflare Workers".

import { writeFile, mkdir, cp } from 'node:fs/promises';
import { join, relative } from 'node:path';
import type { TimberPlatformAdapter, TimberConfig } from './types';

/** Options for the Cloudflare Workers adapter. */
export interface CloudflareAdapterOptions {
  /**
   * Cloudflare compatibility date.
   * @default Current date in YYYY-MM-DD format at build time.
   */
  compatibilityDate?: string;

  /**
   * Additional compatibility flags.
   * @default ['nodejs_compat']
   */
  compatibilityFlags?: string[];

  /**
   * Custom wrangler.jsonc fields to merge.
   * Overrides generated values.
   */
  wrangler?: Record<string, unknown>;
}

/**
 * Create a Cloudflare Workers adapter.
 *
 * @example
 * ```ts
 * import { cloudflare } from '@timber/app/adapters/cloudflare'
 *
 * export default {
 *   output: 'server',
 *   adapter: cloudflare(),
 * }
 * ```
 */
export function cloudflare(options: CloudflareAdapterOptions = {}): TimberPlatformAdapter {
  return {
    name: 'cloudflare',

    async buildOutput(config: TimberConfig, buildDir: string) {
      const outDir = join(buildDir, 'cloudflare');
      await mkdir(outDir, { recursive: true });

      // Copy client assets to static output
      const clientDir = join(buildDir, 'client');
      const staticDir = join(outDir, 'static');
      await mkdir(staticDir, { recursive: true });
      await cp(clientDir, staticDir, { recursive: true }).catch(() => {
        // Client dir may not exist in static+noJS mode
      });

      // Generate the Workers entry point
      const workerEntry = generateWorkerEntry(buildDir, outDir);
      await writeFile(join(outDir, '_worker.ts'), workerEntry);

      // Generate wrangler.jsonc
      const wranglerConfig = generateWranglerConfig(config, options);
      await writeFile(join(outDir, 'wrangler.jsonc'), JSON.stringify(wranglerConfig, null, 2));
    },

    // Default no-op. wrapWithExecutionContext() replaces this per-request
    // with a function that routes to ctx.waitUntil().
    waitUntil(_promise: Promise<unknown>) {},
  };
}

/**
 * Wrap a timber request handler to bind the Cloudflare execution context
 * for `waitUntil()` support. Called from the generated worker entry.
 */
export function wrapWithExecutionContext(
  adapter: TimberPlatformAdapter,
  handler: (req: Request) => Promise<Response>
): ExportedHandler<Record<string, unknown>> {
  return {
    async fetch(
      request: Request,
      _env: Record<string, unknown>,
      ctx: ExecutionContext
    ): Promise<Response> {
      // Bind the adapter's waitUntil to the Workers execution context
      const originalWaitUntil = adapter.waitUntil;
      adapter.waitUntil = (promise: Promise<unknown>) => {
        ctx.waitUntil(promise);
      };

      try {
        return await handler(request);
      } finally {
        // Restore (in case adapter is reused across isolate resets)
        adapter.waitUntil = originalWaitUntil;
      }
    },
  };
}

// ─── Exported helpers (used by tests and build) ─────────────────────────────

/** @internal Exported for testing. */
export function generateWorkerEntry(buildDir: string, outDir: string): string {
  const serverEntryRelative = relative(outDir, join(buildDir, 'server', 'entry.js'));

  return `// Generated by @timber/app/adapters/cloudflare
// Do not edit — this file is regenerated on each build.

import { wrapWithExecutionContext } from '@timber/app/adapters/cloudflare'
import { handler, adapter } from '${serverEntryRelative}'

export default wrapWithExecutionContext(adapter, handler)
`;
}

/** @internal Exported for testing. */
export function generateWranglerConfig(
  config: TimberConfig,
  options: CloudflareAdapterOptions
): Record<string, unknown> {
  const compatDate = options.compatibilityDate ?? new Date().toISOString().slice(0, 10);

  const flags = options.compatibilityFlags ?? ['nodejs_compat'];

  const base: Record<string, unknown> = {
    name: 'timber-app',
    main: '_worker.ts',
    compatibility_date: compatDate,
    compatibility_flags: flags,
    assets: {
      directory: './static',
    },
  };

  // Merge user overrides
  if (options.wrangler) {
    return { ...base, ...options.wrangler };
  }

  return base;
}

// ─── Cloudflare Workers type stubs ───────────────────────────────────────────
// Minimal type declarations so this file compiles without @cloudflare/workers-types.
// In production builds, users install @cloudflare/workers-types themselves.

declare global {
  interface ExecutionContext {
    waitUntil(promise: Promise<unknown>): void;
    passThroughOnException(): void;
  }

  interface ExportedHandler<Env = Record<string, unknown>> {
    fetch?(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> | Response;
  }
}
