// Generated compression module template for self-hosted deployments.
//
// This file generates a standalone ESM module (_compress.mjs) that is
// written to the build output during adapter buildOutput(). It's imported
// by the Nitro entry and preview server at runtime.
//
// Uses CompressionStream (Web API) for gzip. Brotli is left to CDNs/reverse
// proxies — at streaming quality levels its ratio advantage is marginal and
// node:zlib buffers output internally, breaking streaming.
// Cloudflare Workers don't need this — the edge auto-compresses.
//
// See design/25-production-deployments.md.

/**
 * Generate a standalone ESM module that exports compressResponse().
 *
 * Written to `_compress.mjs` during buildOutput. Imported by the Nitro entry
 * and preview server.
 *
 * @internal Exported for testing.
 */
export function generateCompressModule(): string {
  return `// Generated by @timber-js/app — response compression for self-hosted deployments.
// Do not edit — this file is regenerated on each build.
// Uses CompressionStream (Web API) for gzip. Brotli is left to CDNs/reverse
// proxies — at streaming quality levels its ratio advantage is marginal and
// node:zlib buffers output internally, breaking streaming.

const COMPRESSIBLE_TYPES = new Set([
  'text/html', 'text/css', 'text/plain', 'text/xml', 'text/javascript',
  'text/x-component', 'application/json', 'application/javascript',
  'application/xml', 'application/xhtml+xml', 'application/rss+xml',
  'application/atom+xml', 'image/svg+xml',
]);

const NO_COMPRESS_STATUSES = new Set([204, 304]);

function negotiateEncoding(acceptEncoding) {
  if (!acceptEncoding) return null;
  const tokens = acceptEncoding.split(',').map(s => s.split(';')[0].trim().toLowerCase());
  // Brotli (br) is intentionally not handled at the application level.
  // At streaming-friendly quality levels (0-4), brotli's ratio advantage over
  // gzip is marginal, and node:zlib's brotli transform buffers output internally.
  // CDNs/reverse proxies apply brotli at higher quality levels on cached responses.
  if (tokens.includes('gzip')) return 'gzip';
  return null;
}

function shouldCompress(response) {
  if (!response.body) return false;
  if (NO_COMPRESS_STATUSES.has(response.status)) return false;
  if (response.headers.has('Content-Encoding')) return false;
  const contentType = response.headers.get('Content-Type');
  if (!contentType) return false;
  const mimeType = contentType.split(';')[0].trim().toLowerCase();
  if (mimeType === 'text/event-stream') return false;
  return COMPRESSIBLE_TYPES.has(mimeType);
}

function compressWithGzip(body) {
  return body.pipeThrough(new CompressionStream('gzip'));
}

export function compressResponse(request, response) {
  if (!shouldCompress(response)) return response;
  const acceptEncoding = request.headers.get('Accept-Encoding') || '';
  const encoding = negotiateEncoding(acceptEncoding);
  if (!encoding) return response;
  const compressedBody = compressWithGzip(response.body);
  const headers = new Headers(response.headers);
  headers.set('Content-Encoding', encoding);
  headers.delete('Content-Length');
  const existingVary = headers.get('Vary');
  if (existingVary) {
    if (!existingVary.toLowerCase().includes('accept-encoding')) {
      headers.set('Vary', existingVary + ', Accept-Encoding');
    }
  } else {
    headers.set('Vary', 'Accept-Encoding');
  }
  return new Response(compressedBody, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}
`;
}
