// Nitro adapter — multi-platform deployment
//
// Covers everything except Cloudflare Workers: Node.js, Bun, Vercel,
// Netlify, AWS Lambda, Deno Deploy, Azure Functions. Nitro handles
// compression, graceful shutdown, static file serving, and platform quirks.
// See design/11-platform.md and design/25-production-deployments.md.

import { writeFile, readFile, mkdir, cp } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { join, relative } from 'node:path';
import type { TimberPlatformAdapter, TimberConfig } from './types';
import { generateCompressModule } from './compress-module.js';
// Inlined from server/asset-headers.ts — adapters are loaded by Node at
// Vite startup time, before Vite's module resolver is available, so cross-
// directory .ts imports don't resolve.
const IMMUTABLE_CACHE = 'public, max-age=31536000, immutable';
const STATIC_CACHE = 'public, max-age=3600, must-revalidate';

function generateHeadersFile(): string {
  return `# Auto-generated by @timber-js/app — static asset cache headers.
# See design/25-production-deployments.md §"CDN / Edge Cache"

/assets/*
  Cache-Control: ${IMMUTABLE_CACHE}

/*
  Cache-Control: ${STATIC_CACHE}
`;
}

// ─── Presets ─────────────────────────────────────────────────────────────────

/**
 * Supported Nitro deployment presets.
 *
 * Each preset maps to a Nitro deployment target. The adapter generates
 * the appropriate configuration and entry point for the selected platform.
 */
export type NitroPreset =
  | 'vercel'
  | 'vercel-edge'
  | 'netlify'
  | 'netlify-edge'
  | 'aws-lambda'
  | 'deno-deploy'
  | 'azure-functions'
  | 'node-server'
  | 'bun';

/** Preset-specific Nitro configuration. */
interface PresetConfig {
  /** Nitro preset name passed to the Nitro build. */
  nitroPreset: string;
  /** Output directory name within the build dir. */
  outputDir: string;
  /** Whether the runtime supports waitUntil. */
  supportsWaitUntil: boolean;
  /** Whether the runtime supports application-level 103 Early Hints. */
  supportsEarlyHints: boolean;
  /** Value for TIMBER_RUNTIME env var. See design/25-production-deployments.md. */
  runtimeName: string;
  /** Additional nitro.config fields for this preset. */
  extraConfig?: Record<string, unknown>;
}

const PRESET_CONFIGS: Record<NitroPreset, PresetConfig> = {
  'vercel': {
    nitroPreset: 'vercel',
    outputDir: '.vercel/output',
    supportsWaitUntil: true,
    supportsEarlyHints: false,
    runtimeName: 'vercel',
    extraConfig: { vercel: { functions: { maxDuration: 30 } } },
  },
  'vercel-edge': {
    nitroPreset: 'vercel-edge',
    outputDir: '.vercel/output',
    supportsWaitUntil: true,
    supportsEarlyHints: false,
    runtimeName: 'vercel-edge',
  },
  'netlify': {
    nitroPreset: 'netlify',
    outputDir: '.netlify/functions-internal',
    supportsWaitUntil: false,
    supportsEarlyHints: false,
    runtimeName: 'netlify',
  },
  'netlify-edge': {
    nitroPreset: 'netlify-edge',
    outputDir: '.netlify/edge-functions',
    supportsWaitUntil: true,
    supportsEarlyHints: false,
    runtimeName: 'netlify-edge',
  },
  'aws-lambda': {
    nitroPreset: 'aws-lambda',
    outputDir: '.output',
    supportsWaitUntil: false,
    supportsEarlyHints: false,
    runtimeName: 'aws-lambda',
  },
  'deno-deploy': {
    nitroPreset: 'deno-deploy',
    outputDir: '.output',
    supportsWaitUntil: true,
    supportsEarlyHints: false,
    runtimeName: 'deno-deploy',
  },
  'azure-functions': {
    nitroPreset: 'azure-functions',
    outputDir: '.output',
    supportsWaitUntil: false,
    supportsEarlyHints: false,
    runtimeName: 'azure-functions',
  },
  'node-server': {
    nitroPreset: 'node-server',
    outputDir: '.output',
    supportsWaitUntil: true,
    // Disabled by default: most node-server deployments sit behind a
    // reverse proxy (nginx, caddy, traefik) that doesn't support 103
    // Early Hints over HTTP/1.1. Sending 103 causes nginx to intermittently
    // treat the response as an error and retry after proxy_connect_timeout
    // (~5s stalls on ~23% of requests). Link headers on the 200 response
    // are the safe fallback — Cloudflare and other CDNs convert them to
    // 103 automatically at the edge (over HTTP/2+ to the browser).
    supportsEarlyHints: false,
    runtimeName: 'node-server',
  },
  'bun': {
    nitroPreset: 'bun',
    outputDir: '.output',
    supportsWaitUntil: true,
    // Disabled for same reason as node-server — reverse proxies choke on 103.
    // Link headers on the 200 response are converted to 103 by CDNs.
    supportsEarlyHints: false,
    runtimeName: 'bun',
  },
};

// ─── Options ─────────────────────────────────────────────────────────────────

/** Options for the Nitro adapter. */
export interface NitroAdapterOptions {
  /**
   * Deployment preset. Determines the target platform.
   * @default 'node-server'
   */
  preset?: NitroPreset;

  /**
   * Additional Nitro configuration to merge into the generated config.
   * Overrides default values for the selected preset.
   */
  nitroConfig?: Record<string, unknown>;
}

// ─── Adapter ─────────────────────────────────────────────────────────────────

/**
 * Create a Nitro-based adapter for multi-platform deployment.
 *
 * Nitro abstracts deployment targets — the same timber.js app can deploy
 * to Vercel, Netlify, AWS, Deno Deploy, or Azure by changing the preset.
 *
 * @example
 * ```ts
 * import { nitro } from '@timber-js/app/adapters/nitro'
 *
 * export default {
 *   output: 'server',
 *   adapter: nitro({ preset: 'vercel' }),
 * }
 * ```
 */
export function nitro(options: NitroAdapterOptions = {}): TimberPlatformAdapter {
  const preset = options.preset ?? 'node-server';
  const presetConfig = PRESET_CONFIGS[preset];
  const pendingPromises: Promise<unknown>[] = [];

  return {
    name: `nitro-${preset}`,

    async buildOutput(config: TimberConfig, buildDir: string) {
      const outDir = join(buildDir, 'nitro');
      await mkdir(outDir, { recursive: true });

      // Copy client assets to public directory.
      // When client JavaScript is disabled, skip .js files — only CSS,
      // fonts, images, and other static assets are needed.
      const clientDir = join(buildDir, 'client');
      const publicDir = join(outDir, 'public');
      await mkdir(publicDir, { recursive: true });
      await cp(clientDir, publicDir, {
        recursive: true,
        filter: config.clientJavascriptDisabled ? (src: string) => !src.endsWith('.js') : undefined,
      }).catch(() => {
        // Client dir may not exist when client JavaScript is disabled
      });

      // Write _headers file for platforms that support it (Netlify, etc.).
      // See design/25-production-deployments.md §"CDN / Edge Cache"
      await writeFile(join(publicDir, '_headers'), generateHeadersFile());

      // Write the build manifest init module (if manifest data was produced).
      if (config.manifestInit) {
        await writeFile(join(outDir, '_timber-manifest-init.js'), config.manifestInit);
      }

      // Write the compression helper module for runtime use.
      // See design/25-production-deployments.md — self-hosted deployments
      // need application-level compression (Cloudflare handles it at the edge).
      await writeFile(join(outDir, '_compress.mjs'), generateCompressModule());

      // Copy rsc/ssr build output into the nitro dir so imports stay local
      // during the Nitro bundling step (avoids broken relative paths in output).
      await cp(join(buildDir, 'rsc'), join(outDir, 'rsc'), { recursive: true });
      await cp(join(buildDir, 'ssr'), join(outDir, 'ssr'), { recursive: true }).catch(() => {});

      // Prepend the manifest assignment directly into the RSC entry so
      // globalThis.__TIMBER_BUILD_MANIFEST__ is set before any module reads it.
      // This must be top-level code, not an import, because rollup tree-shakes
      // side-effect-only globalThis assignments from imported modules.
      if (config.manifestInit) {
        const rscEntry = join(outDir, 'rsc', 'index.js');
        const rscContent = await readFile(rscEntry, 'utf-8');
        await writeFile(rscEntry, `${config.manifestInit}\n${rscContent}`);
      }

      // Generate the Nitro entry point (imports from ./rsc/ within nitro dir)
      const entry = generateNitroEntry(buildDir, outDir, preset);
      await writeFile(join(outDir, 'entry.ts'), entry);

      // Run the Nitro build to produce a production-ready server bundle.
      // The output goes to dist/nitro/.output/server/index.mjs (for node-server preset).
      // Config is passed programmatically — no nitro.config.ts file needed.
      await runNitroBuild(outDir, preset, options.nitroConfig);
    },

    // Only presets that produce a locally-runnable server get preview().
    // Serverless presets (vercel, netlify, aws-lambda, etc.) have no
    // local runtime — Vite's built-in preview is the fallback.
    preview: LOCALLY_PREVIEWABLE.has(preset)
      ? async (_config: TimberConfig, buildDir: string) => {
          // Generate a standalone preview server that uses Node's built-in
          // HTTP server. The Nitro entry.ts can't be run directly because
          // it imports h3 (a Nitro dependency not available at runtime).
          const previewScript = generatePreviewScript(buildDir, preset);
          const scriptPath = join(buildDir, 'nitro', '_preview-server.mjs');
          await writeFile(scriptPath, previewScript);

          const command = preset === 'bun' ? 'bun' : 'node';
          await spawnNitroPreview(command, [scriptPath], join(buildDir, 'nitro'));
        }
      : undefined,

    waitUntil: presetConfig.supportsWaitUntil
      ? (promise: Promise<unknown>) => {
          const tracked = promise.catch((err) => {
            console.error('[timber] waitUntil promise rejected:', err);
          });
          pendingPromises.push(tracked);
        }
      : undefined,
  };
}

// ─── Entry Generation ────────────────────────────────────────────────────────

/** @internal Exported for testing. */
export function generateNitroEntry(
  buildDir: string,
  outDir: string,
  preset: NitroPreset,
  hasManifestInit = false
): string {
  // The RSC entry is the main request handler — it exports the fetch handler as default.
  // rsc/ is copied into the nitro dir so the import is local.
  // The manifest init is prepended to rsc/index.js before the nitro build,
  // so globalThis.__TIMBER_BUILD_MANIFEST__ is set before any code reads it.
  const serverEntryRelative = './rsc/index.js';
  const runtimeName = PRESET_CONFIGS[preset].runtimeName;
  const earlyHints = PRESET_CONFIGS[preset].supportsEarlyHints;

  // On node-server and bun, wrap the handler with ALS so the pipeline
  // can send 103 Early Hints via res.writeEarlyHints(). Other presets
  // either don't support 103 or handle it at the CDN level.
  const handlerCall = earlyHints
    ? `  const nodeRes = event.node?.res
  const earlyHintsSender = (typeof nodeRes?.writeEarlyHints === 'function')
    ? (links) => { try { nodeRes.writeEarlyHints({ link: links }) } catch {} }
    : undefined

  const webResponse = earlyHintsSender
    ? await runWithEarlyHintsSender(earlyHintsSender, () => handler(webRequest))
    : await handler(webRequest)`
    : `  const webResponse = await handler(webRequest)`;

  // Build manifest init must be imported before the handler so that
  // globalThis.__TIMBER_BUILD_MANIFEST__ is set when the virtual module evaluates.
  // ESM guarantees imports are evaluated in order.
  const manifestImport = hasManifestInit ? "import './_timber-manifest-init.js'\n" : '';

  return `// Generated by @timber-js/app/adapters/nitro
// Do not edit — this file is regenerated on each build.

${manifestImport}import { defineEventHandler } from 'nitro/h3'
import handler, { runWithEarlyHintsSender } from '${serverEntryRelative}'
import { compressResponse } from './_compress.mjs'

// Set TIMBER_RUNTIME for instrumentation.ts conditional SDK initialization.
// See design/25-production-deployments.md §"TIMBER_RUNTIME".
process.env.TIMBER_RUNTIME = '${runtimeName}'

export default defineEventHandler(async (event) => {
  // h3 v2: event.req is the Web Request
  const webRequest = event.req
${handlerCall}
  return compressResponse(webRequest, webResponse)
})
`;
}

/** @internal Exported for testing. */
export function generateNitroConfig(
  preset: NitroPreset,
  userConfig?: Record<string, unknown>
): string {
  const presetConfig = PRESET_CONFIGS[preset];

  const config: Record<string, unknown> = {
    preset: presetConfig.nitroPreset,
    entry: './entry.ts',
    output: { dir: presetConfig.outputDir },
    // Static asset cache headers — hashed assets are immutable, others get 1h.
    // See design/25-production-deployments.md §"CDN / Edge Cache"
    routeRules: {
      '/assets/**': { headers: { 'Cache-Control': IMMUTABLE_CACHE } },
    },
    ...presetConfig.extraConfig,
    ...userConfig,
  };

  const configJson = JSON.stringify(config, null, 2);

  return `// Generated by @timber-js/app/adapters/nitro
// Do not edit — this file is regenerated on each build.

import { defineNitroConfig } from 'nitro/config'

export default defineNitroConfig(${configJson})
`;
}

// ─── Preview ─────────────────────────────────────────────────────────────────

/** Presets that produce a locally-runnable server entry. */
const LOCALLY_PREVIEWABLE = new Set<NitroPreset>(['node-server', 'bun']);

/**
 * Generate a standalone preview server script that uses Node's built-in
 * HTTP server. This bypasses Nitro entirely — the Nitro entry.ts imports
 * h3 which isn't available outside a Nitro build. For local preview we
 * just need to serve static files and route requests to the RSC handler.
 *
 * @internal Exported for testing.
 */
export function generatePreviewScript(buildDir: string, preset: NitroPreset): string {
  const rscEntryRelative = relative(join(buildDir, 'nitro'), join(buildDir, 'rsc', 'index.js'));
  const rscEntry = rscEntryRelative.startsWith('.') ? rscEntryRelative : './' + rscEntryRelative;
  const publicDir = './public';
  const manifestInitPath = './_timber-manifest-init.js';
  const runtimeName = PRESET_CONFIGS[preset].runtimeName;

  return `// Generated by @timber-js/app — standalone preview server.
// Uses Node's built-in HTTP server to serve static assets and route
// dynamic requests through the RSC handler. No Nitro/h3 dependency.

import { createServer } from 'node:http';
import { readFile, stat } from 'node:fs/promises';
import { join, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { existsSync } from 'node:fs';

// Set runtime before importing the handler.
process.env.TIMBER_RUNTIME = '${runtimeName}';

// Load the build manifest if it exists.
const __dirname = fileURLToPath(new URL('.', import.meta.url));
const manifestPath = join(__dirname, '${manifestInitPath}');
if (existsSync(manifestPath)) {
  await import('${manifestInitPath}');
}

// Import the RSC handler (default export is the fetch-like handler).
const { default: handler, runWithEarlyHintsSender } = await import('${rscEntry}');

// Import compression helper for self-hosted response compression.
const { compressResponse } = await import('./_compress.mjs');

const MIME_TYPES = {
  '.html': 'text/html',
  '.js': 'application/javascript',
  '.mjs': 'application/javascript',
  '.css': 'text/css',
  '.json': 'application/json',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
  '.otf': 'font/otf',
  '.webp': 'image/webp',
  '.avif': 'image/avif',
  '.webm': 'video/webm',
  '.mp4': 'video/mp4',
  '.txt': 'text/plain',
  '.xml': 'application/xml',
  '.wasm': 'application/wasm',
};

const publicDir = join(__dirname, '${publicDir}');
const port = parseInt(process.env.PORT || '3000', 10);
const host = process.env.HOST || process.env.HOSTNAME || 'localhost';

const server = createServer(async (req, res) => {
  const url = new URL(req.url || '/', \`http://\${host}:\${port}\`);

  // Try serving static files from the public directory first.
  const filePath = join(publicDir, url.pathname);
  // Prevent path traversal.
  if (filePath.startsWith(publicDir)) {
    try {
      const fileStat = await stat(filePath);
      if (fileStat.isFile()) {
        const ext = extname(filePath);
        const contentType = MIME_TYPES[ext] || 'application/octet-stream';
        const body = await readFile(filePath);
        // Hashed assets get immutable cache, others get short cache.
        const cacheControl = url.pathname.startsWith('/assets/')
          ? 'public, max-age=31536000, immutable'
          : 'public, max-age=3600, must-revalidate';
        res.writeHead(200, {
          'Content-Type': contentType,
          'Content-Length': body.length,
          'Cache-Control': cacheControl,
        });
        res.end(body);
        return;
      }
    } catch {
      // File not found — fall through to the RSC handler.
    }
  }

  // Convert Node request to Web Request.
  const headers = new Headers();
  for (const [key, value] of Object.entries(req.headers)) {
    if (value) {
      if (Array.isArray(value)) {
        for (const v of value) headers.append(key, v);
      } else {
        headers.set(key, value);
      }
    }
  }

  let body = undefined;
  if (req.method !== 'GET' && req.method !== 'HEAD') {
    body = await new Promise((resolve) => {
      const chunks = [];
      req.on('data', (chunk) => chunks.push(chunk));
      req.on('end', () => resolve(Buffer.concat(chunks)));
    });
  }

  const webRequest = new Request(url.href, {
    method: req.method,
    headers,
    body,
    duplex: body ? 'half' : undefined,
  });

  try {
    // Support 103 Early Hints when available.
    const earlyHintsSender = (typeof res.writeEarlyHints === 'function')
      ? (links) => { try { res.writeEarlyHints({ link: links }); } catch {} }
      : undefined;

    const rawResponse = earlyHintsSender && runWithEarlyHintsSender
      ? await runWithEarlyHintsSender(earlyHintsSender, () => handler(webRequest))
      : await handler(webRequest);

    // Compress the response for self-hosted deployments.
    const webResponse = compressResponse(webRequest, rawResponse);

    // Write the response back to the Node response.
    res.writeHead(webResponse.status, Object.fromEntries(webResponse.headers.entries()));

    if (webResponse.body) {
      const reader = webResponse.body.getReader();
      const pump = async () => {
        while (true) {
          const { done, value } = await reader.read();
          if (done) { res.end(); return; }
          res.write(value);
        }
      };
      await pump();
    } else {
      res.end();
    }
  } catch (err) {
    console.error('[timber preview] Request error:', err);
    if (!res.headersSent) {
      res.writeHead(500, { 'Content-Type': 'text/plain' });
    }
    res.end('Internal Server Error');
  }
});

server.listen(port, host, () => {
  console.log();
  console.log('  ⚡ timber preview server running at:');
  console.log();
  console.log(\`    ➜  http://\${host}:\${port}\`);
  console.log();
});
`;
}

/** Command descriptor for Nitro preview — testable without spawning. */
export interface NitroPreviewCommand {
  command: string;
  args: string[];
  cwd: string;
}

/** @internal Exported for testing. */
export function generateNitroPreviewCommand(
  buildDir: string,
  preset: NitroPreset
): NitroPreviewCommand | null {
  if (!LOCALLY_PREVIEWABLE.has(preset)) return null;

  const nitroDir = join(buildDir, 'nitro');
  const entryPath = join(nitroDir, 'entry.ts');

  const command = preset === 'bun' ? 'bun' : 'node';
  return {
    command,
    args: [entryPath],
    cwd: nitroDir,
  };
}

/**
 * Run the Nitro production build using the programmatic API.
 * Uses dynamic import so nitro is only loaded at build time.
 * Externalizes the timber RSC/SSR output — those files are pre-built
 * by timber and have internal references that nitro's bundler can't follow.
 */
async function runNitroBuild(
  nitroDir: string,
  preset: NitroPreset,
  userConfig?: Record<string, unknown>
): Promise<void> {
  const presetConfig = PRESET_CONFIGS[preset];
  const { createNitro, build: nitroBuild, prepare, copyPublicAssets } = await import('nitro');

  const nitro = await createNitro({
    rootDir: nitroDir,
    preset: presetConfig.nitroPreset,
    // Use renderer.entry so Nitro wraps our handler with its server runtime
    // (HTTP server, static file serving, graceful shutdown, etc.).
    // Using `entry` directly would bypass the Nitro server runtime.
    renderer: { entry: join(nitroDir, 'entry.ts') },
    output: { dir: join(nitroDir, presetConfig.outputDir) },
    routeRules: {
      '/assets/**': { headers: { 'Cache-Control': IMMUTABLE_CACHE } },
    },
    // Don't bundle the timber RSC/SSR build output — it has its own
    // internal file references that nitro's bundler can't follow.
    // Mark them as external so rollup leaves the imports as-is.
    rollupConfig: {
      external: [/\.\.\/rsc\//],
    },
    ...presetConfig.extraConfig,
    ...userConfig,
  });

  await prepare(nitro);
  await copyPublicAssets(nitro);
  await nitroBuild(nitro);
  await nitro.close();
}

/** Spawn a Nitro preview process and pipe stdio. */
function spawnNitroPreview(command: string, args: string[], cwd: string): Promise<void> {
  return new Promise<void>((resolve, reject) => {
    const child = execFile(command, args, { cwd }, (err) => {
      if (err) reject(err);
      else resolve();
    });
    child.stdout?.pipe(process.stdout);
    child.stderr?.pipe(process.stderr);
  });
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Get the preset configuration for a given preset name.
 * @internal Exported for testing.
 */
export function getPresetConfig(preset: NitroPreset): PresetConfig {
  return PRESET_CONFIGS[preset];
}
