/**
 * timber-build-manifest — Vite sub-plugin for CSS asset manifest generation.
 *
 * Provides `virtual:timber-build-manifest` which exports a BuildManifest
 * mapping route segment file paths to their CSS output chunks.
 *
 * - Dev mode: exports an empty manifest (Vite HMR handles CSS).
 * - Build mode: populated from Vite's .vite/manifest.json after client build.
 *
 * Design docs: 18-build-system.md §"Build Manifest", 02-rendering-pipeline.md §"Early Hints"
 */

import type { Plugin } from 'vite';
import type { PluginContext } from '../index.js';
import type { BuildManifest } from '../server/build-manifest.js';

const VIRTUAL_MODULE_ID = 'virtual:timber-build-manifest';
const RESOLVED_VIRTUAL_ID = `\0${VIRTUAL_MODULE_ID}`;

/**
 * Vite's manifest.json entry shape (subset we need).
 * See https://vite.dev/guide/backend-integration.html
 */
interface ViteManifestEntry {
  file: string;
  css?: string[];
  imports?: string[];
}

/**
 * Parse Vite's .vite/manifest.json into a BuildManifest.
 *
 * Walks each entry and collects its `css` array (which already includes
 * transitive CSS from imported modules). Keys are input file paths
 * (relative to project root), values are output CSS URLs (absolute paths).
 */
export function parseViteManifest(
  viteManifest: Record<string, ViteManifestEntry>,
  base: string
): BuildManifest {
  const css: Record<string, string[]> = {};

  for (const [inputPath, entry] of Object.entries(viteManifest)) {
    if (entry.css && entry.css.length > 0) {
      css[inputPath] = entry.css.map((cssPath) => base + cssPath);
    }
  }

  return { css };
}

/**
 * Create the timber-build-manifest Vite plugin.
 *
 * Hooks: resolveId, load
 */
export function timberBuildManifest(ctx: PluginContext): Plugin {
  return {
    name: 'timber-build-manifest',

    resolveId(id: string) {
      const cleanId = id.startsWith('\0') ? id.slice(1) : id;

      if (cleanId === VIRTUAL_MODULE_ID) {
        return RESOLVED_VIRTUAL_ID;
      }

      if (cleanId.endsWith(`/${VIRTUAL_MODULE_ID}`)) {
        return RESOLVED_VIRTUAL_ID;
      }

      return null;
    },

    load(id: string) {
      if (id !== RESOLVED_VIRTUAL_ID) return null;

      // In dev mode, return empty manifest — Vite HMR handles CSS.
      // In build mode, the manifest data comes from PluginContext
      // (populated by the adapter after client build).
      const manifest = ctx.buildManifest ?? { css: {} };

      return [
        '// Auto-generated build manifest — do not edit.',
        '// Generated by timber-build-manifest plugin.',
        '',
        `const manifest = ${JSON.stringify(manifest, null, 2)};`,
        '',
        'export default manifest;',
      ].join('\n');
    },
  };
}
